/*
 * Generated file
 *
 * Generated from: yang module name: device-provider-impl yang module local name: device-provider-impl Generated by:
 * org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator Generated at: Thu Aug 21 14:52:21 PDT 2014
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.discovery.config.device_provider.impl;

public class DeviceProviderModuleFactory extends
org.opendaylight.discovery.config.device_provider.impl.AbstractDeviceProviderModuleFactory {

}
