/*
 * Copyright (c) 2014 Ciena Corporation and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
/*
* Generated file
*
* Generated from: yang module name: discovery-provider-impl yang module local name: discovery-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon May 09 14:36:03 EDT 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.discovery_provider.impl;
public class DiscoveryProviderModuleFactory extends org.opendaylight.controller.config.yang.config.discovery_provider.impl.AbstractDiscoveryProviderModuleFactory {

}
