/*
 * Generated file
 *
 * Generated from: yang module name: identification-provider-impl yang module local name: identification-provider-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Thu Aug 21 12:26:41 PDT 2014
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.lifecycle.config.lifecycle_provider.impl;

public class LifecycleProviderModuleFactory extends
        org.opendaylight.lifecycle.config.lifecycle_provider.impl.AbstractLifecycleProviderModuleFactory {

}
